import fs from 'fs';
const original = fs.readFileSync('./tests/csv/data/original.csv', 'utf8');
const extracted = fs.readFileSync('./tests/csv/data/extracted.csv', 'utf8');
console.log('---original---');
console.log(JSON.stringify(original));
console.log('---original chars---');
console.log([...original.slice(0,100)].map(c=>c.charCodeAt(0)));
console.log('---extracted---');
console.log(JSON.stringify(extracted));
console.log('---extracted chars---');
console.log([...extracted.slice(0,100)].map(c=>c.charCodeAt(0)));
console.log('---original lines---');
console.log(original.split(/\r?\n/).map((line, i)=>`${i+1}:${JSON.stringify(line)}`));
console.log('---extracted lines---');
console.log(extracted.split(/\r?\n/).map((line, i)=>`${i+1}:${JSON.stringify(line)}`));
